spring.application.name=eteeapp
# Database Configuration
spring.datasource.url=jdbc:postgresql://ep-morning-meadow-ahopyvbh-pooler.c-3.us-east-1.aws.neon.tech/eteeap-db?sslmode=require&prepareThreshold=0
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NbqU12mVovsc


# Postgres driver
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Use the PostgreSQL dialect (matches Neon/Postgres)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Fix Postgres LOB access issue ("Large Objects may not be used in auto-commit mode")
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Optional: explicitly expose the JDBC URL for Hibernate dialect detection
jakarta.persistence.jdbc.url=${spring.datasource.url}


spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.enabled=true

# File storage configuration
file.upload-dir=./uploads


